blank_issues_enabled: true
tos_violation:
- name: Copyright infringement?
  url: https://bananas.openttd.org/manager/tos
  about: Please report violations to abuse@openttd.org. Ideally by the copyright holder, and at least including links and references so we can verify the violation.
